"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&5*c9sj&+0!&&78)n23co=hh+oq44ep8whe!67w*#f*sj^2uc*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0','209.74.88.131', 'luvbazar.com', 'www.luvbazar.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'region',
    'products',
    'orders',
    'users',
    'cart',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_count',
                'ecommerce.context_processors.site_info'

            ],
            'libraries': {
                'custom_filter': 'ecommerce.templatetags.custom_filter',
            },
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'
#STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# WhiteNoise static file serving with compression and long-term caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MAX_AGE = 31536000  # 1 year
WHITENOISE_ALLOW_ALL_ORIGINS = True
# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8000',
]

# Security settings for development
ALLOWED_HOSTS = ['*']

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom authentication backend for phone number login
AUTHENTICATION_BACKENDS = [
    'users.backends.PhoneNumberBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep default backend for backward compatibility
]

# SSL Commerz Payment Gateway Configuration
SSL_COMMERZ_STORE_ID = os.getenv('SSL_COMMERZ_STORE_ID', 'israb672a4e32dfea5')
SSL_COMMERZ_STORE_PASSWORD = os.getenv('SSL_COMMERZ_STORE_PASSWORD', 'israb672a4e32dfea5@ssl')
SSL_COMMERZ_BASE_URL = 'https://sandbox.sslcommerz.com/gwprocess/v4/api.php'  # Sandbox
# For production, use: SSL_COMMERZ_BASE_URL = 'https://securepay.sslcommerz.com/gwprocess/v4/api.php'
SSL_COMMERZ_SESSION_API = 'https://sandbox.sslcommerz.com/gwprocess/v4/gateway.php'  # Sandbox
# For production, use: SSL_COMMERZ_SESSION_API = 'https://securepay.sslcommerz.com/gwprocess/v4/gateway.php'

# Site configuration
SITE_URL = os.getenv('SITE_URL', 'https://luvbazar.com')
# For production, use the production SSL Commerz URLs
SSL_COMMERZ_BASE_URL = 'https://securepay.sslcommerz.com/gwprocess/v4/api.php'
SSL_COMMERZ_SESSION_API = 'https://securepay.sslcommerz.com/gwprocess/v4/gateway.php'

SMS_API_URL = "" # Replace with your gateway's URL
SMS_API_KEY = "u53QpjUF5xnqPScdmyp9"

# Shared cache using Redis — required for OTP to work across all gunicorn workers
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "TIMEOUT": 300,  # Default 5 minutes (OTP expiry)
    }
}
SMS_SENDER_ID = "8809648909088"