# Generated by Django 6.0.1 on 2026-05-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_check_in_date_order_check_out_date_and_more'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_zip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address',
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district'),
        ),
        migrations.AddField(
            model_name='order',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.division'),
        ),
        migrations.AddField(
            model_name='order',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.union'),
        ),
        migrations.AddField(
            model_name='order',
            name='upazilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla'),
        ),
    ]
