# Generated by Django 6.0.1 on 2026-06-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_apartment_remove_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='room',
        ),
    ]
