# Generated by Django 6.0.1 on 2026-02-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('action_text', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
