# Generated by Django 6.0.1 on 2026-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sitesetting_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
