# Generated by Django 6.0.3 on 2026-05-03 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_check_in_date_order_check_out_date_and_more'),
        ('products', '0005_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
