# Generated by Django 6.0.3 on 2026-05-03 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_room_category_image_customer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite'), ('deluxe', 'Deluxe Room'), ('penthouse', 'Penthouse')], default='single', max_length=20)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('size_sqft', models.IntegerField(blank=True, help_text='Room size in square feet', null=True)),
                ('floor_number', models.IntegerField(default=1)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_tv', models.BooleanField(default=True)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/rooms/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
    ]
