# Generated by Django 6.0.1 on 2026-06-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_room'),
        ('products', '0006_category_image_customer_image_product_offer_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
