# Generated by Django 5.2.16 on 2026-07-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['serial', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['serial', 'rating', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='serial',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='serial',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
