# Generated by Django 5.2.16 on 2026-07-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_products_ca_slug_da4386_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='background_carousel/')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('action_text', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
